In [1]:
pwd()

'C:\\Users\\fawad\\Desktop\\piaic\\q2\\assignments'

In [2]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
arr[arr % 2 == 1] = -1


In [6]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
arr.reshape(2, -1)


array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

In [3]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

In [8]:
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [9]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [10]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [11]:
np.concatenate([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [13]:
common([a,b])

NameError: name 'common' is not defined

In [14]:
np.intersect1d(a,b)

array([2, 4])

In [15]:
np.setdiff1d(a,b)

array([1, 3, 5, 6])

In [16]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int32),)

In [17]:
 np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
a-b

array([-6,  0, -7,  0, -4,  0, -6,  0, -4, -2])

In [20]:
a*b

array([ 7,  4, 30,  4, 21, 16, 27, 16, 45, 48])

In [21]:
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [24]:
a1=a.reshape(5,2)

In [25]:
b1=b.reshape(5,2)

In [26]:
a1*b1

array([[ 7,  4],
       [30,  4],
       [21, 16],
       [27, 16],
       [45, 48]])

In [28]:
a1.dot(b1)

ValueError: shapes (5,2) and (5,2) not aligned: 2 (dim 1) != 5 (dim 0)

In [30]:
a*=3
a

array([ 9, 18, 27, 18, 27, 36, 27, 36, 45, 54])

In [31]:
a

array([ 9, 18, 27, 18, 27, 36, 27, 36, 45, 54])

In [32]:
a+=3

In [33]:
a

array([12, 21, 30, 21, 30, 39, 30, 39, 48, 57])

In [34]:
a-3

array([ 9, 18, 27, 18, 27, 36, 27, 36, 45, 54])

In [35]:
a+3

array([15, 24, 33, 24, 33, 42, 33, 42, 51, 60])

In [36]:
a1.dtype.name

'int32'

In [37]:
a1.sum()

327

a1.min()

In [38]:
a1.min()

12

In [39]:
a[:6:2] = 1000

In [40]:
a


array([1000,   21, 1000,   21, 1000,   39,   30,   39,   48,   57])

In [42]:
a1.shape

(5, 2)

In [44]:
a1.ravel()

array([1000,   21, 1000,   21, 1000,   39,   30,   39,   48,   57])

In [45]:
a1

array([[1000,   21],
       [1000,   21],
       [1000,   39],
       [  30,   39],
       [  48,   57]])

In [46]:
a1.T

array([[1000, 1000, 1000,   30,   48],
       [  21,   21,   39,   39,   57]])

In [47]:
np.vstack([a1,b1])

array([[1000,   21],
       [1000,   21],
       [1000,   39],
       [  30,   39],
       [  48,   57],
       [   7,    2],
       [  10,    2],
       [   7,    4],
       [   9,    4],
       [   9,    8]])

In [48]:
np.hsplit(a,2)

[array([1000,   21, 1000,   21, 1000]), array([39, 30, 39, 48, 57])]

In [51]:
id(a1)

198065832

In [53]:
a[a<1000]

array([21, 21, 39, 30, 39, 48, 57])

In [55]:
np.where(a==1000)

(array([0, 2, 4], dtype=int32),)

In [56]:
a[::-1]


array([  57,   48,   39,   30,   39, 1000,   21, 1000,   21, 1000])

In [57]:
np.mean(a)

325.5

In [58]:
np.median(a)

43.5

In [61]:
np.std(a)

441.6870498441176

In [62]:
amax,amin=a.max(), a.min()

In [64]:
aS=(a-amin)/(amax-amin)
aS

array([1.        , 0.        , 1.        , 0.        , 1.        ,
       0.01838611, 0.00919305, 0.01838611, 0.02757916, 0.03677222])

In [65]:
np.percentile(a,q=[5,95])

array([  21., 1000.])

In [66]:
np.corrcoef(a,b)

array([[1.        , 0.43116713],
       [0.43116713, 1.        ]])

In [67]:
np.isnan(a).any()

False

In [77]:
a.dtype.name

'int32'

### 


In [71]:
a[0]=0

In [78]:
a3 = np.random.uniform(low=0.5, high=13.3, size=(10,))

In [79]:
a3

array([ 3.62637768,  2.97642512,  5.52141647,  6.32650721,  5.75605402,
        1.26600627, 10.12930146,  8.25229044,  0.80268829,  6.06076765])

In [80]:
a3[0]=np.nan

In [84]:
np.isnan(a3).sum()

1

In [85]:
np.isnan(a3).any()

True

In [86]:
np.unique(a)

array([   0,   21,   30,   39,   48,   57, 1000])

In [87]:
np.unique(a,return_counts=True)

(array([   0,   21,   30,   39,   48,   57, 1000]),
 array([1, 2, 1, 2, 1, 1, 2]))